(function(){'use strict';
const engine=window.OobFitCheckEngine,form=document.querySelector('[data-fit-form]');if(!engine||!form)return;
const q=s=>document.querySelector(s),result=q('[data-fit-result]'),validation=q('[data-fit-validation]'),missingTitle=q('[data-fit-missing-title]'),missingCopy=q('[data-fit-missing-copy]'),taskChoices=form.querySelector('[data-fit-task-choices]'),groups=[...form.querySelectorAll('fieldset:not(.fit-task-choices)')],submit=form.querySelector('[data-fit-submit]'),workInput=form.querySelector('[name="workLabel"]'),urlInput=form.querySelector('[name="contextUrl"]'),researchStatus=q('[data-fit-research-status]'),copyButton=q('[data-fit-copy-result]'),printButton=q('[data-fit-print]'),status=q('[data-fit-status]'),reduce=window.matchMedia?window.matchMedia('(prefers-reduced-motion: reduce)'):{matches:false};let current=null;
const f={kicker:q('[data-fit-kicker]'),score:q('[data-fit-score]'),title:q('[data-fit-title]'),summary:q('[data-fit-copy]'),profile:q('[data-fit-profile]'),why:q('[data-fit-why]'),dimensions:q('[data-fit-dimensions]'),role:q('[data-fit-role]'),human:q('[data-fit-human]'),watch:q('[data-fit-watch]'),factors:q('[data-fit-factors]'),research:q('[data-fit-research]'),researchTitle:q('[data-fit-research-title]'),researchEvidence:q('[data-fit-research-evidence]'),researchBoundary:q('[data-fit-research-boundary]'),blockers:q('[data-fit-blockers]'),blockerList:q('[data-fit-blocker-list]'),nextTitle:q('[data-fit-next-title]'),nextCopy:q('[data-fit-next-copy]'),plan:q('[data-fit-plan]'),nextLink:q('[data-fit-next-link]'),supportLink:q('[data-fit-support-link]'),work:q('[data-fit-work]')};
function addDesc(el,id){const ids=new Set((el.getAttribute('aria-describedby')||'').split(/\s+/).filter(Boolean));ids.add(id);el.setAttribute('aria-describedby',[...ids].join(' '));}
function removeDesc(el,id){const ids=(el.getAttribute('aria-describedby')||'').split(/\s+/).filter(x=>x&&x!==id);ids.length?el.setAttribute('aria-describedby',ids.join(' ')):el.removeAttribute('aria-describedby');}
function clearValidation(){taskChoices.removeAttribute('aria-invalid');taskChoices.querySelectorAll('input').forEach(x=>{x.removeAttribute('aria-invalid');removeDesc(x,validation.id)});groups.forEach(g=>{g.removeAttribute('aria-invalid');g.querySelectorAll('input').forEach(x=>{x.removeAttribute('aria-invalid');removeDesc(x,validation.id)})});const job=form.querySelector('[name="jobType"]');job.removeAttribute('aria-invalid');removeDesc(job,validation.id);workInput.removeAttribute('aria-invalid');removeDesc(workInput,validation.id);validation.hidden=true;}
function validate(){const missing=groups.filter(g=>!g.querySelector('input:checked')),tasks=form.querySelectorAll('[name="task"]:checked'),job=form.querySelector('[name="jobType"]');clearValidation();if(!workInput.value.trim()){missing.push(workInput);workInput.setAttribute('aria-invalid','true');addDesc(workInput,validation.id)}if(!tasks.length){missing.push(taskChoices);taskChoices.setAttribute('aria-invalid','true');taskChoices.querySelectorAll('input').forEach(x=>{x.setAttribute('aria-invalid','true');addDesc(x,validation.id)})}if(!job.value){missing.push(job);job.setAttribute('aria-invalid','true');addDesc(job,validation.id)}missing.filter(x=>x.tagName==='FIELDSET'&&x!==taskChoices).forEach(g=>{g.setAttribute('aria-invalid','true');const x=g.querySelector('input');x.setAttribute('aria-invalid','true');addDesc(x,validation.id)});if(!missing.length)return true;result.hidden=true;missingTitle.textContent=`${missing.length} ${missing.length===1?'answer is':'answers are'} still needed.`;missingCopy.textContent='Complete the highlighted questions, then review this possible use again.';validation.hidden=false;validation.focus({preventScroll:true});validation.scrollIntoView({behavior:reduce.matches?'auto':'smooth',block:'center'});return false;}
function stateLabel(s){return s==='strong'?'Clear':s==='mixed'?'Check':'Resolve';}
function renderDimensions(items){f.dimensions.replaceChildren();items.forEach(x=>{const a=document.createElement('article');a.className='fit-dimension';a.dataset.state=x.state;const p=document.createElement('p'),b=document.createElement('strong');p.textContent=x.label;b.textContent=x.detail;a.append(p,b);f.dimensions.append(a)})}
function renderFactors(items){f.factors.replaceChildren();items.forEach(x=>{const a=document.createElement('article');a.className='fit-factor-row';a.dataset.state=x.state;const left=document.createElement('div'),h=document.createElement('h4'),d=document.createElement('p'),m=document.createElement('p'),badge=document.createElement('span');h.textContent=x.label;d.textContent=x.detail;left.append(h,d);m.className='fit-factor-meaning';m.textContent=x.meaning;badge.className='fit-factor-state';badge.textContent=stateLabel(x.state);a.append(left,m,badge);f.factors.append(a)})}
function renderResearch(r){f.researchEvidence.replaceChildren();if(!r){f.research.hidden=true;return}f.research.hidden=false;f.researchTitle.textContent=r.title&&r.title!==r.host?`Reviewed: ${r.title}`:`Reviewed: ${r.host}`;r.evidence.forEach(x=>{const a=document.createElement('article'),h=document.createElement('h4'),p=document.createElement('p');a.className='fit-research-row';h.textContent=x.title;p.textContent=x.detail;a.append(h,p);f.researchEvidence.append(a)});f.researchBoundary.textContent=r.boundary;}
function renderBlockers(items){f.blockerList.replaceChildren();f.blockers.hidden=!items.length;items.forEach(x=>{const a=document.createElement('article'),h=document.createElement('h4'),p=document.createElement('p');a.className='fit-blocker-card';h.textContent=x.title;p.textContent=x.detail;a.append(h,p);f.blockerList.append(a)})}
function renderPlan(items){f.plan.replaceChildren();items.forEach(x=>{const li=document.createElement('li'),num=document.createElement('span'),body=document.createElement('div'),h=document.createElement('h4'),p=document.createElement('p'),done=document.createElement('p'),strong=document.createElement('strong');li.className='fit-plan-step';num.className='fit-plan-number';num.textContent=x.number;h.textContent=x.action;p.textContent=x.instruction;done.className='fit-done-when';strong.textContent='Done when: ';done.append(strong,document.createTextNode(x.doneWhen));body.append(h,p,done);li.append(num,body);f.plan.append(li)})}
function render(b){current=b;f.kicker.textContent=b.kicker;f.work.textContent=b.workLabel;f.score.textContent=b.score;f.title.textContent=b.title;f.summary.textContent=b.summary;f.profile.textContent=b.profile;f.why.textContent=b.why;f.role.textContent=b.role;f.human.textContent=b.humanResponsibility;f.watch.textContent=b.watch;f.nextTitle.textContent=b.next.title;f.nextCopy.textContent=b.next.copy;f.nextLink.textContent=b.next.label;f.nextLink.href=b.next.href;f.supportLink.href=b.next.href;renderDimensions(b.factors);renderFactors(b.factors);renderResearch(b.research);renderBlockers(b.blockers);renderPlan(b.plan);status.textContent='';result.hidden=false;result.focus({preventScroll:true});result.scrollIntoView({behavior:reduce.matches?'auto':'smooth',block:'start'});}
async function researchPage(value,context){const normalized=engine.normalizePublicUrl(value);if(!normalized)throw new Error('Please enter a valid public http or https URL.');const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),14000);try{const res=await fetch(`https://r.jina.ai/${normalized}`,{headers:{Accept:'text/plain'},signal:ctrl.signal});if(!res.ok)throw new Error(`Public page review returned ${res.status}.`);const r=engine.analyzePublicPage(await res.text(),normalized,context);if(!r)throw new Error('The public page did not return enough readable content to evaluate.');return r}finally{clearTimeout(timer)}}
function briefText(b){const lines=['AI Task Fit Brief','',`Work checked: ${b.workLabel}`,`Decision: ${b.score}`,b.title,b.summary,'','Best role for AI',b.role,'','Keep human responsibility here',b.humanResponsibility,'','What drove this result'];b.factors.forEach(x=>lines.push(`${x.label} — ${x.detail}: ${x.meaning}`));if(b.research){lines.push('',`Public page reviewed: ${b.research.title||b.research.host}`);b.research.evidence.forEach(x=>lines.push(`${x.title}: ${x.detail}`));lines.push(b.research.boundary)}if(b.blockers.length){lines.push('','Resolve before testing');b.blockers.forEach(x=>lines.push(`${x.title}: ${x.detail}`))}lines.push('','What to do next');b.plan.forEach(x=>lines.push(`${x.number}. ${x.action}`,x.instruction,`Done when: ${x.doneWhen}`));lines.push('',`${b.next.title} ${b.next.copy}`);return lines.join('\n');}
form.addEventListener('submit',async e=>{e.preventDefault();if(!validate())return;const data=new FormData(form),a=Object.fromEntries(data),tasks=data.getAll('task'),context={tasks,jobType:a.jobType};let research=null;submit.disabled=true;submit.setAttribute('aria-busy','true');researchStatus.textContent='';try{if(a.contextUrl){researchStatus.textContent='Reviewing the public page you provided…';try{research=await researchPage(a.contextUrl,context);researchStatus.textContent=`Public page reviewed: ${research.title||research.host}.`}catch(err){researchStatus.textContent=`${err.message} Your fit result will use your assessment answers only.`}}const brief=engine.evaluate({answers:a,tasks,jobType:a.jobType,research});brief.workLabel=a.workLabel.trim().replace(/\s+/g,' ').slice(0,120);render(brief)}catch{researchStatus.textContent='The brief could not be built in this browser. Your answers were not sent. Please try again or clear the form.'}finally{submit.disabled=false;submit.removeAttribute('aria-busy')}});
form.addEventListener('change',e=>{const g=e.target.closest('fieldset');if(e.target.matches('[name="task"]')){taskChoices.removeAttribute('aria-invalid');taskChoices.querySelectorAll('input').forEach(x=>{x.removeAttribute('aria-invalid');removeDesc(x,validation.id)})}if(e.target.matches('[name="jobType"]')){e.target.removeAttribute('aria-invalid');removeDesc(e.target,validation.id)}if(g){g.removeAttribute('aria-invalid');g.querySelectorAll('input').forEach(x=>{x.removeAttribute('aria-invalid');removeDesc(x,validation.id)})}if(!groups.some(x=>x.getAttribute('aria-invalid')==='true'))validation.hidden=true;if(!result.hidden)result.hidden=true;current=null;status.textContent=''});
workInput.addEventListener('input',()=>{workInput.removeAttribute('aria-invalid');removeDesc(workInput,validation.id);if(!result.hidden)result.hidden=true;current=null;status.textContent=''});
urlInput.addEventListener('input',()=>{researchStatus.textContent=urlInput.value?'Only this public URL will be sent for page review. Your assessment answers stay in this browser.':''});printButton.addEventListener('click',()=>window.print());copyButton.addEventListener('click',async()=>{if(!current)return;try{await navigator.clipboard.writeText(briefText(current));status.textContent='AI Task Fit Brief copied.'}catch{status.textContent='Copy was not available in this browser. Use Save free result as PDF instead.'}});form.addEventListener('reset',()=>setTimeout(()=>{clearValidation();result.hidden=true;current=null;researchStatus.textContent='';status.textContent='';submit.disabled=false;submit.removeAttribute('aria-busy');const first=form.querySelector('input');first.scrollIntoView({behavior:reduce.matches?'auto':'smooth',block:'center'});first.focus({preventScroll:true})},0));
})();
